### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by al-muftah** [iMokhles/IMSign#1]
Trying to resign app but waiting for long time with nothing happens 

http://b.top4top.net/p_151wdow1.png

**Comment by iMokhles** [comment]
Hi, check the new version here
https://github.com/iMokhles/IMSign/releases/tag/v1.1b

and tel me what happens

**Comment by ArabBoz** [comment]
same problem not working also i used https://github.com/iMokhles/IMSign/releases/tag/v1.1b not working

**Comment by ArabBoz** [comment]
how to fix it

**Comment by al-muftah** [comment]
Still same issue

**Comment by Nas-au** [comment]
Same issue here

**Comment by al-muftah** [comment]
please resolve the issue

**Comment by iMokhles** [comment]
Hi all ( fixed this issue )
v1.2 is live now : https://github.com/iMokhles/IMSign/releases/tag/v1.2
