### ISSUE TITLE
not work on iPad i got message not support iPad

### ISSUE THREAD

**Issue by ArabBoz** [iMokhles/IMSign#2]
dear i installed on my iPad i got message sorry, device is currently not supported.

how i can install it without jailbreak

**Comment by iMokhles** [comment]
Which app ?!

**Comment by ArabBoz** [comment]
whatsapp

**Comment by iMokhles** [comment]
Yes IMSign supports only installing the app but not bypassing the activation

**Comment by ArabBoz** [comment]
anyway to install whatsapp without jailbreak
